version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - redis
    environment:
      MONGODB_URI: "mongodb://root:example@mongodb:27017"
      REDIS_URI: "redis://redis:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "50051:50051" # gRPC
      - "8080:8080"   # REST
    depends_on:
      - mongodb
      - redis
    environment:
      MONGODB_URI: "mongodb://root:example@mongodb:27017"
      REDIS_URI: "redis://redis:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
  redis_data:
